### ISSUE TITLE
Failed to flush outgoing items: NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by JakeFromTheDark** [logstash-plugins/logstash-output-elasticsearch#157]
# Introduction
Using `elasticsearch` output plugin with `node` protocol and multicast discovery requires `@host=nil`:
```
  # The plugin will use multicast discovery to connect to Elasticsearch
  # when using `protocol => node` without setting a host...
```

# Symptoms
But then Logstash goes into a loop with this error message:
```
{:timestamp=>"2015-05-25T14:43:40.667000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>1, :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["/opt/logstash/vendor/local_gems/9b366c45/logstash-output-concur_elasticsearch-0.2.5/lib/logstash/outputs/concur_elasticsearch.rb:480:in `flush'", "/opt/logstash/vendor/local_gems/9b366c45/logstash-output-concur_elasticsearch-0.2.5/lib/logstash/outputs/concur_stud/buffer.rb:229:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/local_gems/9b366c45/logstash-output-concur_elasticsearch-0.2.5/lib/logstash/outputs/concur_stud/buffer.rb:225:in `buffer_flush'", "/opt/logstash/vendor/local_gems/9b366c45/logstash-output-concur_elasticsearch-0.2.5/lib/logstash/outputs/concur_stud/buffer.rb:199:in `buffer_flush'", "/opt/logstash/vendor/local_gems/9b366c45/logstash-output-concur_elasticsearch-0.2.5/lib/logstash/outputs/concur_stud/buffer.rb:165:in `buffer_receive'", "/opt/logstash/vendor/local_gems/9b366c45/logstash-output-concur_elasticsearch-0.2.5/lib/logstash/outputs/concur_elasticsearch.rb:440:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/outputs/base.rb:88:in `handle'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/outputs/base.rb:79:in `worker_setup'"], :level=>:warn, :file=>"logstash/outputs/concur_stud/buffer.rb", :line=>"247", :method=>"buffer_flush"}
```

# Root cause
Of course, because lines 461, 464 and 518 was trying to log a string with `@host[@client_idx]`, but `@host` is `nil`!

# Suggested solution
Do not try to use `@host[...]` whenever `@host` is `nil`. 
 
# Versions
```
$ /opt/logstash/bin/logstash --version
logstash 1.5.0
```

**Comment by jsvd** [comment]
this has been fixed in https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/59f96175182ffda453a5c7acb7d6714e742b47d1
