### ISSUE TITLE
Failed to install template and NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by lijuan8** [logstash-plugins/logstash-output-elasticsearch#163]
I am just trying to connect logstash and elasticsearch. 

the logstash config solr.conf:
input{
  stdin{
      type=>"solr"
  }
}
output{
        stdout{codec=>rubydebug}
        elasticsearch{cluster=>"ada_elasticsearch"}
}

start logstash by using:
 bin/logstash -f solr.conf

in the console, i saw this: 

INFO: [logstash-0.0.0.0-4989-7990] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.21.1:9300]}
May 29, 2015 12:19:38 PM org.elasticsearch.discovery.DiscoveryService doStart
INFO: [logstash-0.0.0.0-4989-7990] ada_elasticsearch/SQicSx22Q6mQGw2Q-n7XPg
May 29, 2015 12:20:08 PM org.elasticsearch.discovery.DiscoveryService waitForInitialState
WARNING: [logstash-0.0.0.0-4989-7990] waited for 30s and no initial state was set by the discovery
May 29, 2015 12:20:08 PM org.elasticsearch.node.internal.InternalNode start
INFO: [logstash-0.0.0.0-4989-7990] started
Failed to install template: waited for [30s] {:level=>:error}
Logstash startup completed

I type "solr log" and saw this event and error message:

solr log (
{
       "message" => "solr log",
      "@version" => "1",
    "@timestamp" => "2015-05-29T19:20:56.769Z",
          "type" => "solr",
          "host" => "0.0.0.0"
}

Failed to flush outgoing items {:outgoing_count=>1, :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["/Users/xxx/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:464:in `flush'", "/Users/xxx/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/Users/xxx/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:216:in `buffer_flush'", "/Users/xxx/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:159:in `buffer_receive'", "/Users/xxx/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:426:in `receive'", "/Users/xxx/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):27:in `output_func'", "/Users/xxxx/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:244:in `outputworker'", "/Users/xxxx/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:warn}

Elasticsearch server: i only changed the cluster.name and node in  /usr/local/opt/elasticsearch/config/elasticsearch.yml 
with:
cluster.name: ada_elasticsearch
node.name: "smoker" 

nothing else changed.

Here is the elasticsearch process:

/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Delasticsearch -Des.foreground=yes -Des.path.home=/usr/local/Cellar/elasticsearch/1.5.2 -cp :/usr/local/Cellar/elasticsearch/1.5.2/libexec/elasticsearch-1.5.2.jar:/usr/local/Cellar/elasticsearch/1.5.2/libexec/*:/usr/local/Cellar/elasticsearch/1.5.2/libexec/sigar/* -Des.config=/usr/local/opt/elasticsearch/config/elasticsearch.yml org.elasticsearch.bootstrap.Elasticsearch

logstash:

60041614  4989  1751   0 12:19PM ttys001    0:16.52 /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Xmx500m -Xss2048k -Djffi.boot.library.path=/Users/xxx/logstash-1.5.0/vendor/jruby/lib/jni -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Dfile.encoding=UTF-8 -Xbootclasspath/a:/Users/xxx/logstash-1.5.0/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/Users/xxx/logstash-1.5.0/vendor/jruby -Djruby.lib=/Users/xxx/logstash-1.5.0/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main --1.9 /Users/xxx/logstash-1.5.0/lib/bootstrap/environment.rb logstash/runner.rb agent -f solr.conf

Thanks!

**Comment by lijuan8** [comment]
I added the following to the solr.conf and message is able to be indexed in elasticsearch

 protocol=>"http"
 bind_host=>"127.0.0.1"
