### ISSUE TITLE
Logstash throws error, service shows not running but process still executes

### ISSUE THREAD

**Issue by iamrudra** [logstash-plugins/logstash-output-elasticsearch#221]
Encountered this when I was trying to get Logstash to push into two different elasticsearch (one cluster and one standalone node). I made a [post](https://discuss.elastic.co/t/multiple-elasticsearch-output-plugins-for-single-logstash-instance/27275) on discuss.elastic.co and followed changed my lumberjack output config to:

```
  output {
    elasticsearch {
      host => "localhost"
      cluster => "my-es-cluster"
    }
    elasticsearch {
      protocol => "http"
      host => "10.xx.xx.xx"
      #cluster => "my-another-cluster"
    }
    stdout { codec => rubydebug }
    }
```

But now I have another error that says:

```
{
    : timestamp=>"2015-08-12T16:00:09.101000-0400",
    : message=>"Failed to flush outgoing items",
    : outgoing_count=>14,
    : exception=>#<Manticore: : SocketException: Connectionrefused>,
    : backtrace=>[
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:35:in `initialize'",
        "org/jruby/RubyProc.java:271:in `call'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:61:in `call'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:225:in `call_once'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:128:in `code'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/manticore.rb:71:in `perform_request'",
        "org/jruby/RubyProc.java:271:in `call'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:190:in `perform_request'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/manticore.rb:54:in `perform_request'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/client.rb:119:in `perform_request'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/bulk.rb:80:in `bulk'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstash/outputs/elasticsearch/protocol.rb:103:in `bulk'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstash/outputs/elasticsearch.rb:505:in `submit'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstash/outputs/elasticsearch.rb:504:in `submit'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstash/outputs/elasticsearch.rb:529:in `flush'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.1-java/lib/logstash/outputs/elasticsearch.rb:528:in `flush'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:219:in `buffer_flush'",
        "org/jruby/RubyHash.java:1341:in `each'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:216:in `buffer_flush'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:112:in `buffer_initialize'",
        "org/jruby/RubyKernel.java:1511:in `loop'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:110:in `buffer_initialize'"
    ],
    : level=>: warn
}{
    : timestamp=>"2015-08-12T16:00:09.101000-0400",
    : message=>"Got error to send bulk of actions: Connection refused",
    : level=>: error
}
```

...which I guess is some network/firewall related issue since I tried telnet on that box from my logstash box over 9200 and it says connection refused. 

But it is weird to see that the logstash service **status** says **it is not running** - which to my understanding is OK since it encountered an exception but when I do `netstat -elntp` it shows me (I'm running Logstash over 443):

> Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
> tcp        0      0 0.0.0.0:443             0.0.0.0:\*               LISTEN      0          231388      10568/java      

Process runs in the background. This can give exceptions like `address already bound` on the next attempt to start Logstash. Also this halts the logstash-forwarder to do anything - it cannot log error for not being able to connect nor can it connect so it just holds on to:
`2015/08/12 16:38:18.256432 Connecting to [xxx.xxx.xxx.xxx]:443 (xxx.xxx.xxx.xxx)`

**Comment by jsvd** [comment]
this seems to be an issue related to packaging and not the es output since the PID is the means to identify that the process is still running.
anyway, closing due to inactivity, please open a new issue if you're observing the same problem
