### ISSUE TITLE
hardcoded port for https?

### ISSUE THREAD

**Issue by nellicus** [logstash-plugins/logstash-output-elasticsearch#262]
using 2.0 beta

```
if [type] == "syslog" {
                        elasticsearch {
                                hosts => ["w530:9200","w530:9201","w530:9202"]
                                index => "logstash-syslog-%{+YYYY.MM.dd}"
                                user => "logstash"
                                password => "secret"
				ssl => true
				keystore => "/opt/elk/PRODSEC/FS/secure/node1.jks"
				keystore_password => "secret"
				truststore => "/opt/elk/PRODSEC/FS/secure/ca-truststore.jks"
				truststore_password => "secret"
                        }
                }
```

```
The error reported is: 
  the scheme https does not accept registry part: w530:9200:9200 (or bad hostname?)
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/jruby/lib/ruby/1.9/uri/generic.rb:214:in `initialize'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/jruby/lib/ruby/1.9/uri/http.rb:84:in `initialize'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/jruby/lib/ruby/1.9/uri/common.rb:214:in `parse'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/jruby/lib/ruby/1.9/uri/common.rb:747:in `parse'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/client.rb:149:in `__extract_hosts'
org/jruby/RubyArray.java:2414:in `map'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/client.rb:145:in `__extract_hosts'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/client.rb:109:in `initialize'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport.rb:26:in `new'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.beta6-java/lib/logstash/outputs/elasticsearch/http_client.rb:109:in `build_client'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.beta6-java/lib/logstash/outputs/elasticsearch/http_client.rb:17:in `initialize'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.beta6-java/lib/logstash/outputs/elasticsearch.rb:256:in `register'
org/jruby/RubyArray.java:1613:in `each'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.beta1-java/lib/logstash/pipeline.rb:164:in `start_outputs'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.beta1-java/lib/logstash/pipeline.rb:83:in `run'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.beta1-java/lib/logstash/agent.rb:155:in `execute'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.beta1-java/lib/logstash/runner.rb:90:in `run'
org/jruby/RubyProc.java:271:in `call'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.beta1-java/lib/logstash/runner.rb:95:in `run'
org/jruby/RubyProc.java:271:in `call'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/task.rb:12:in `initialize'
```

**Comment by suyograo** [comment]
@untergeek can you check this out please?

**Comment by untergeek** [comment]
It looks like we need to completely deprecate port for this to work correctly.  Port is what's causing issues:

https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/http_client.rb#L89-L92

If we're going with `hosts` (where it's an array of `["host1:port1","host2:port2"]`) instead of `host` and `port`, we need to document that and completely remove all references to `port`.  I can pursue this, but only with the team's understanding and blessing.

@suyograo ?

**Comment by ph** [comment]
I think we should make it backward compatibl, but we could mark the settings as `:deprecated` and in a future version make it `:obsolete`?

**Comment by untergeek** [comment]
I think it should be `:obsolete` now, and save a step.  But if the consensus is to keep it, I think we could take the existing code:

```
      uris = hosts.map do |host|
        proto = client_settings[:ssl] ? "https"  : "http"
        "#{proto}://#{host}:#{port}#{client_settings[:path]}"
      end
```

And mutate it to detect colons in `host`:

```
      uris = hosts.map do |host|
        proto = client_settings[:ssl] ? "https"  : "http"
        if !(host =~ /:/).nil?
          # If there's a colon, don't use #{port}
          "#{proto}://#{host}#{client_settings[:path]}"
        else
          "#{proto}://#{host}:#{port}#{client_settings[:path]}"
        end
      end
```

What do you think, @ph, @suyograo ?

**Comment by suyograo** [comment]
I am +1 on removing `ports` and just using `hosts` with port info in there. Since we are releasing a 2.0, this can be a breaking change. We already break bwc with `host` being renamed to `hosts`. /cc @jordansissel

**Comment by suyograo** [comment]
@untergeek ^^

**Comment by untergeek** [comment]
\o/

Did you want me to make this sweeping edit, @suyograo?  It is a big one...

**Comment by untergeek** [comment]
Also, do we need to put 9200 in as a default if only host names are used?

**Comment by suyograo** [comment]
@untergeek go for it.. @andrewvc is on vacation. 
Yes, good catch, we need to append 9200 for default if its not there in the hostname.
