### ISSUE TITLE
Template management for ES 2.0 issue

### ISSUE THREAD

**Issue by untergeek** [logstash-plugins/logstash-output-elasticsearch#265]
When I run the test suite against 2.0.0-rc1, I see this:

```
[2015-10-08 15:29:54,469][DEBUG][action.index             ] [Scarlet Witch] [some-path][3], node[Xaz0lhiiSRSwIb89-rwVQQ], [P], s[STARTED]: Failed to execute [index {[some-path][_template][logstash], source[{"template":"logstash-*","settings":{"index.refresh_interval":"5s"},"mappings":{"_default_":{"_all":{"enabled":true,"omit_norms":true},"dynamic_templates":[{"message_field":{"match":"message","match_mapping_type":"string","mapping":{"type":"string","index":"analyzed","omit_norms":true}}},{"string_fields":{"match":"*","match_mapping_type":"string","mapping":{"type":"string","index":"analyzed","omit_norms":true,"fields":{"raw":{"type":"string","index":"not_analyzed","ignore_above":256}}}}}],"properties":{"@version":{"type":"string","index":"not_analyzed"},"geoip":{"type":"object","dynamic":true,"properties":{"location":{"type":"geo_point"}}}}}}}]}]
org.elasticsearch.indices.InvalidTypeNameException: mapping type name [_template] can't start with '_'
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:325)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:313)
	at org.elasticsearch.index.mapper.MapperService.documentMapperWithAutoCreate(MapperService.java:473)
	at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:396)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:191)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:535)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:434)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by untergeek** [comment]
I don't know what happened, but I can't reproduce this.  The plugin passes all template tests against 2.0.0-rc1 just fine:

```
index template expected behavior
  creates .raw field from any string field which is not_analyzed
  make [geoip][location] a geo_point
  does not create .raw field for the message field
  numbers dynamically map to a numeric type and permit range queries
  should index stopwords like 'at'
  permits phrase searching on string fields
```

All green.
