### ISSUE TITLE
Problem with jdbc input and elastic search output plugin.

### ISSUE THREAD

**Issue by jinleileiking** [logstash-plugins/logstash-output-elasticsearch#272]
here is my create conf:

```
input {
  jdbc {
    jdbc_driver_library => "./mysql-connector-java-5.1.36-bin.jar"
    jdbc_driver_class => "com.mysql.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://10.36.253.127:6159/yingjian_duin"
    jdbc_user => "uWFL9Wg6159"
    jdbc_password => "Pm3a64WROxgCqQxIO"
    statement => "select product_id, product_title, product_name from product where product_title != '' or product_name != '' and _isdelete != 0 and product_status = 1"
#statement => "select id, user_id from user_web"
    jdbc_paging_enabled => "true"
    jdbc_page_size => "50000"
  }
}


output {
  stdout {
    codec => rubydebug
  }
  elasticsearch {
      action => "create"
      protocol => "http"
      index => "duin"
      document_type => "product"
      document_id => "%{product_id}"
  }
}
```

works well.

then update.conf: 

```
input {
  jdbc {
    jdbc_driver_library => "./mysql-connector-java-5.1.36-bin.jar"
    jdbc_driver_class => "com.mysql.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://10.36.253.127:6159/yingjian_duin"
    jdbc_user => "uWFL9Wg6159"
    jdbc_password => "Pm3a64WROxgCqQxIO"
    statement => "select product_id, product_title, product_name from product where product_title != '' or product_name != '' and _isdelete != 0 and product_status = 1"
#statement => "select id, user_id from user_web"
    jdbc_paging_enabled => "true"
    jdbc_page_size => "50000"
  }
}


output {
  stdout {
    codec => rubydebug
  }
  elasticsearch {
      action => "update"
      protocol => "transport"
      index => "duin"
      document_type => "product"
      document_id => "%{product_id}"
  }
}
```

shows  the error:

```
Got error to send bulk of actions: no constructor for arguments (org.jruby.RubyString,org.jruby.RubyString,org.jruby.RubyBignum) on Java::OrgElasticsearchActionUpdate::UpdateRequest {:level=>:error}
Failed to flush outgoing items {:outgoing_count=>433, :exception=>"NameError", :backtrace=>["/home/lk/tools/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch/protocol.rb:272:in `build_request'", "/home/lk/tools/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch/protocol.rb:236:in `bulk'", "org/jruby/RubyArray.java:1613:in `each'", "/home/lk/tools/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch/protocol.rb:235:in `bulk'", "/home/lk/tools/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:542:in `submit'", "/home/lk/tools/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:566:in `flush'", "/home/lk/tools/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/home/lk/tools/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:216:in `buffer_flush'", "/home/lk/tools/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:193:in `buffer_flush'", "/home/lk/tools/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:159:in `buffer_receive'", "/home/lk/tools/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:531:in `receive'", "/home/lk/tools/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):27:in `output_func'", "/home/lk/tools/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:244:in `outputworker'", "/home/lk/tools/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:warn}


```

**Comment by jinleileiking** [comment]
➜  bin git:(master) ✗ ./logstash -V
logstash 1.5.4

logstash-output-elasticsearch (1.1.0)

logstash-input-jdbc (1.0.0)

es: 1.7.1

**Comment by Da-Wei** [comment]
Nice bug @jinleileiking !
document_id needs to be cast to a String. http seems to be more permissive !
Pending a fix, you can use http protocol instead of transport in your update conf like in your create conf.

**Comment by andrewvc** [comment]
Since we no longer support transport this bug is irrelevant.
