### ISSUE TITLE
LS 1.5.5 fails with 'Got error to send bulk of actions: Cannot find Serializer for class' and 'Failed to flush outgoing items'

### ISSUE THREAD

**Issue by ThomasdOtreppe** [logstash-plugins/logstash-output-elasticsearch#300]
Logstash worked for a few hours then keeps failing with:
```
{:timestamp=>"2015-11-06T14:06:50.508000-0700", :message=>"Got error to send bulk of actions: Cannot find Serializer for class: org.jruby.RubyObject", :level=>:error}
{:timestamp=>"2015-11-06T14:06:50.508000-0700", :message=>"Failed to flush outgoing items", :outgoing_count=>8, :exception=>"JrJackson::ParseError", :backtrace=>["com/jrjackson/JrJacksonBase.java:83:in `generate'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jrjackson-0.3.6/lib/jrjackson/jrjackson.rb:59:in `dump'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json/adapters/jr_jackson.rb:20:in `dump'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:25:in `dump'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json.rb:136:in `dump'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:102:in `__bulkify'", "org/jruby/RubyArray.java:2414:in `map'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:102:in `__bulkify'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/bulk.rb:82:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch/protocol.rb:104:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:542:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:541:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:566:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:565:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1479:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
```

Output configuration:
```
output {
        elasticsearch {
                host => [ localhost ]
                protocol => "http"
        }
}
```

It seems related to #294 and #298.

System info:
- Ubuntu 14.04.3 64bit LTS
- Logstash 1.5.5
- Official JDK 8
- ElasticSearch 1.7.3

**Comment by tomsommer** [comment]
Dup of #294

**Comment by guyboertje** [comment]
Please see #298 re: config and example data.

There must be a line of data that results in a different execution path through the pipeline.

**Comment by guyboertje** [comment]
@ThomasdOtreppe - can you locate the first line of data that LS generates the error on?

**Comment by ThomasdOtreppe** [comment]
I'm pretty sure those 3 lines generate the error since I didn't see them in Kibana when other logs were in there (and saw them in an ouput file I create along with sending them to ElasticSearch):
```
{"message":"'htpasswd' checksum test failed for /etc/nginx/.htpasswd","@version":"1","@timestamp":"2015-01-10T16:35:07.000Z","host":"ubuntu","path":"/var/log/monit.log","type":"monit","loglevel":"error"}
{"message":"'logstash_conf' timestamp was not changed for /etc/logstash/conf.d","@version":"1","@timestamp":"2015-01-10T16:35:07.000Z","host":"ubuntu","path":"/var/log/monit.log","type":"monit","loglevel":"info"}
{"message":"'logstash' process PID changed from 18232 to 18462","@version":"1","@timestamp":"2015-01-10T16:35:07.000Z","host":"ubuntu","path":"/var/log/monit.log","type":"monit","loglevel":"error"}
```

Here are the 3 lines coming from the log file:
```
[MST Nov 10 09:35:07] error    : 'htpasswd' checksum test failed for /etc/nginx/.htpasswd
[MST Nov 10 09:35:07] error    : 'logstash' process PID changed from 18232 to 18462
[MST Nov 10 09:35:07] info     : 'logstash_conf' timestamp was not changed for /etc/logstash/conf.d
```

And here is the config file for monit:
```
input {
        file {
                path => '/var/log/monit.log'
                sincedb_path => "/var/logstash/monit.db"
                sincedb_write_interval => 1
                type => 'monit'
        }
}

filter {
        if [type] == 'monit' {
                grok {
                        match => [ 'message', '%{SYSLOG5424SD:timestamp_noyear} %{LOGLEVEL:loglevel}%{SPACE}: %{GREEDYDATA:message}' ]
                        overwrite => 'message'
                }
                ruby {
                        init => "require 'time'"
                        code => "Time.strptime(event['timestamp_noyear'], '[%Z %b %d %H:%M:%S]') - Time.now > 2500000 ? event['year'] = Time.now.year - 1 : event['year'] = Time.now.year"
                }
                mutate {
                        add_field => {
                                "timestamp" => "%{timestamp_noyear} %{year}"
                        }
                }
                date {
                        match => [ "timestamp", "[zzz MMM DD HH:mm:ss] yyyy", "[zzz MMM  D HH:mm:ss] yyyy" ]
                        locale => "en"
                        remove_field => [ "timestamp", "timestamp_noyear", "year" ]
                }
        }
}
```

**Comment by guyboertje** [comment]
This is NOT related to #294.

@ThomasdOtreppe - Please look at https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/298#issuecomment-156066999

Fundamentally, the JrJackson error `Cannot find Serializer for class: org.jruby.RubyObject` means that somewhere in one or more of the buffered Events that are being bulk transmitted to ES there is an Ruby Object that can't be serialized.

If you run LS with the `--debug` option and capture the output we will be able to find it.

**Comment by ThomasdOtreppe** [comment]
It doesn't happen anymore since I've filtered N/A from geoip filter.

**Comment by guyboertje** [comment]
NOTE TO ALL FUTURE VIEWER OF THIS ISSUE:

The error message of `Cannot find Serializer for class: ` and/or `Cannot serialize instance of:` are caused when our serializer encounters a Ruby object that is unserializable in the Event object graph.

This is an abnormal case where a failure in the some part of the inputs -> filters -> outputs chain inserts such an instance.  Use --debug to troubleshoot this, look for this character sequence in the output `#<` with a Ruby FQ class name directly after.  LogStash::Event and LogStash::Timestamp are serializable so you should look for some other fully qualified class name.

These JRuby objects are serializable:
```
Nil
JavaProxy
String
Boolean
Float
Fixnum
Bignum
BigDecimal
Hash
Array
Struct
Time
```
and any object that implements these methods
```
to_json_data
to_time
to_h
to_hash
to_a
to_json
```
