### ISSUE TITLE
default output plugin for elasticsearch, can't create new index because of problem with geoip

### ISSUE THREAD

**Issue by mdiehm** [logstash-plugins/logstash-output-elasticsearch#310]
Hi,

I run the software on debian 8.2 (jessie 64-Bit) from the official repositories:
logstash: 2.0
elasticsearch: 2.0.0

As a sidenote: it takes quite long for logstash to run even the simplest commands:
/opt/logstash# time bin/logstash --help /dev/null
real    0m14.428s
user    0m53.244s
sys     0m1.268s

anyway the errors I get are:

Logstash error message:
status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"mapping [_default_]", "caused_by"=>{
"type"=>"mapper_parsing_exception", "reason"=>"Mapping definition for [geoip] has unsupported parameters:  [path : full]"}}}}, :level=>:warn

Elasticsearch error message:
[2015-11-18 17:52:55,218][DEBUG][action.admin.indices.create] [wapiti] [logstash-2015.11.18] failed to create
MapperParsingException[mapping [_default_]]; nested: MapperParsingException[Mapping definition for [geoip] has unsupported parameters:  [path : full]];
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:359)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:225)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:188)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: MapperParsingException[Mapping definition for [geoip] has unsupported parameters:  [path : full]]
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:267)
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:261)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:317)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:228)
        at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:137)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:211)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:192)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:177)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:229)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:356)

and on the elasticsearch side:
[2015-11-18 17:52:55,218][DEBUG][action.admin.indices.create] [wapiti] [logstash-2015.11.18] failed to create
MapperParsingException[mapping [_default_]]; nested: MapperParsingException[Mapping definition for [geoip] has unsupported parameters:  [path : full]];
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:359)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:225)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:188)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: MapperParsingException[Mapping definition for [geoip] has unsupported parameters:  [path : full]]
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:267)
        at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:261)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:317)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:228)
        at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:137)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:211)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:192)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:177)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:229)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:356)

any ideas?

**Comment by untergeek** [comment]
```
"Mapping definition for [geoip] has unsupported parameters: [path : full]"
```

…means that you're using an old template.  

### If you're using the stock Logstash template:
Add `template_overwrite => true` in your output configuration, then the update will be automatic.

### If you have a custom template:
You may not have a custom template to worry about. If you do, ensure that you've updated your custom template to not have the offending mapping, and you can point to it via Logstash with the associated configuration options, and use `template_overwrite => true` the same way.

**Comment by ackermann** [comment]
Since Issue #94 has been closed in April and there hasn't been a release since March 26th; do you think a release of the remove-path-full branch might be a good idea now that people are starting to upgrade to ES 2.0?

**Comment by untergeek** [comment]
@ackermann I do not know what you're referring to, but there most assuredly have been [releases since March 26th](https://rubygems.org/gems/logstash-output-elasticsearch/versions), and recent releases of the template included with the plugin [do not have the `path : full` mapping in them](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json#L82-L91).

That's why I recommended `template_overwrite => true`: an old template stored in Elasticsearch's metadata did not get updated in subsequent releases. Logstash will not presume to remove or upgrade (yet) a template in place without this setting.  We actually covered this in a [blog post yesterday](https://www.elastic.co/blog/logstash-lines-2015-11-17) (see item 2).

**Comment by ackermann** [comment]
@untergeek please excuse for the confusion. The commit that resolved #94 was in tylerjl's fork - which is the one with no releases since March. I should have checked more thoroughly.

**Comment by mdiehm** [comment]
@untergeek Thanks for the hint, this fixed the issue. It is actually a little confusing since I thought logstash would do that after upgrading by default. I see the risk in doing so for people with custom templates. But as the majority - this is my suggestion - uses the default you could probably rethink the choice or be very explicit in the upgrade documentation.
Thanks again.

**Comment by suyograo** [comment]
This has been added to the upgrade docs https://www.elastic.co/guide/en/logstash/current/_upgrading_logstash_and_elasticsearch_to_2_0.html
