### ISSUE TITLE
Logstash Crashes : Manticore::SocketException: Connection refused : Unable to connect to ES

### ISSUE THREAD

**Issue by akamanocha** [logstash-plugins/logstash-output-elasticsearch#360]
I am using logstash on every node and shipping to elasticsearch directly.

If elasticsearch dies for some reason, I get the following error in logstash and it dies

My versions are
logstash 1.5.4
logstash-output-elasticearch 1.0.0
elasticsearch 1.7.1
java version 1.8.0_60

> {:timestamp=>"2016-02-03T16:46:58.944000+0530", :message=>"Failed to flush outgoing items", :outgoing_count=>4037, :exception=>"Manticore::ClientProtocolException", :backtrace=>["/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:35:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:70:in `call'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:245:in `call_once'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:148:in `code'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/manticore.rb:71:in `perform_request'", "org/jruby/RubyProc.java:271:in `call'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:190:in `perform_request'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/manticore.rb:54:in `perform_request'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/client.rb:119:in `perform_request'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/bulk.rb:80:in `bulk'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch/protocol.rb:104:in `bulk'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:542:in `submit'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:541:in `submit'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:566:in `flush'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:565:in `flush'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:216:in `buffer_flush'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:193:in `buffer_flush'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1511:in `loop'", "/home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
Manticore::SocketException: Connection refused
       initialize at /home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:35
             call at org/jruby/RubyProc.java:271
             call at /home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:70
        call_once at /home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:245
             code at /home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:148
  perform_request at /home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/manticore.rb:71
             call at org/jruby/RubyProc.java:271
  perform_request at /home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:190
  perform_request at /home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/manticore.rb:54
  perform_request at /home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/client.rb:119
             bulk at /home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/bulk.rb:80
             bulk at /home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch/protocol.rb:104
           submit at /home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:542
           submit at /home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:541
      retry_flush at /home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:736
         register at /home/ubuntu/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.7-java/lib/logstash/outputs/elasticsearch.rb:480

My logstash config is 

> input {
    file {
        path => ["/home/ubuntu/logs/nb-credits*","/tmp/logs/access_log*"] # change number 6
        codec => multiline {

                pattern => "(^\d+\serror)|(^.+Exception .+)|(^.+Exception: .+)|(^\s+at .+)|(^\s+... \d+ more)|(^\s*Caused by:.+)"

                what => "previous"

        }
    }
}

output { 
    elasticsearch {
        protocol => "http"
        host => "nb-prod-logboard.nbtools.com" 
        port => "9200"
    }
}

filter omitted.
My architecture is pretty simple
Input File -> logstash -> ES

and just wanted to keep it that simple.

**End ask can I do something that my logstash doesnt die if ES dies**

bin/plugin update logstash-output-elasticsearch upgrades me to 1.1.0 from but is the issue fixed there?
Is it something to do with the configuration below (I am not using any of those since they are commented)

> #       max_retries => 100
#       retry_max_items => 5000
#       retry_max_interval => 5

I assume there are default for those anyways. And flush_size default being 5000, correct?

**Comment by akamanocha** [comment]
Hey,

Any insight?
Would very much appreciate any help here....

**Comment by andrewvc** [comment]
Apologies for the extreme delay. This plugin has been significantly improved since your post. Please try the latest version and let us know if you still have issues.
