### ISSUE TITLE
Upsert can not be json

### ISSUE THREAD

**Issue by wenerme** [logstash-plugins/logstash-output-elasticsearch#379]
**upsert**
- Value type is string
- Default value is ""

Set upsert content for update mode. Create a new document with this parameter as json string if document_id doesn’t exists

```
input {
    file {
        path => "/path/to/trace.log"
        start_position => beginning
        type => "test"
    }
}


output{
  elasticsearch{
    action => "update"
    document_id => "%{[message]}"
    index => "test"
    document_type => "test"
    upsert => '{"data":"%{[message]}"}'
    doc_as_upsert => true
  }
  stdout{
    codec => rubydebug{
      metadata => true
    }
  }
}
```

**Exception**

```
[2016-03-01 15:04:13,773][INFO ][rest.suppressed          ] /_bulk Params: {}
java.lang.IllegalArgumentException: Malformed action/metadata line [1], expected a simple value for field [_upsert] but found [START_OBJECT]
    at org.elasticsearch.action.bulk.BulkRequest.add(BulkRequest.java:361)
    at org.elasticsearch.rest.action.bulk.RestBulkAction.handleRequest(RestBulkAction.java:88)
    at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
```

But

```
...
upsert => '"%{[message]}"'
...
```

Still got exception 

```
[2016-03-01 15:08:47,745][INFO ][rest.suppressed          ] /_bulk Params: {}
java.lang.IllegalArgumentException: Action/metadata line [1] contains an unknown parameter [_upsert]
    at org.elasticsearch.action.bulk.BulkRequest.add(BulkRequest.java:351)
    at org.elasticsearch.rest.action.bulk.RestBulkAction.handleRequest(RestBulkAction.java:88)
    at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
```

> Logstash 2.2.2
> ES 2.2.0

**Comment by andrewvc** [comment]
Yes, this is correct and not a bug. You should use filters to convert your upserted data into a proper event.

**Comment by Rickvanderwaal** [comment]
What filter should i use to convert my upserted data into a proper event ? And how will i use it in the upsert field of the elasticsearch output?

**Comment by maayan-samari** [comment]
any update answer for this issue? the documentations and examples are lacking and it would be great for a real example, great thanks!
