### ISSUE TITLE
Improve handling of response codes from Elasticsearch

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-elasticsearch#496]
LS 5.0

```
[2016-10-26T12:20:22,245][ERROR][logstash.outputs.elasticsearch] Got a bad response code from server, but this code is not considered retryable. Request will be dropped {:code=>403}
```

For errors that are not retryable causing requests till drop immediately, it will be helpful to provide more than just the http status code, but also the http response message and body of content so it's easier for the end user to tell exactly what the response error is.

**Comment by roadrunner** [comment]
would be great if we can specify retryable error codes at input configuration
when consuming from a message queue, i think it's important to be able to re-queue event in certain cases instead of dropping

**Comment by ppf2** [comment]
LS 5.1.1

This will be especially helpful for users using X-pack security.  Elasticsearch / X-pack security provides a very descriptive message (root cause) detailing the exact privilege that is missing from the user role.  But this is completely lost in Logstash logging and only a 403 response code is provided.

```
[2016-12-28T17:09:56,008][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<URI::HTTPS:0x2c0ba922 URL:https://~hidden~:~hidden~@instance_id.us-east-1.aws.found.io:9243>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :error=>"Got response code '403' contact Elasticsearch at URL 'https://~hidden~:~hidden~@instance_id.us-east-1.aws.found.io:9243/'"}
```

Ideally, the output plugin will be passing through the root cause message from Elasticsearch to its own logging, eg.

```
{"error":{"root_cause":[{"type":"security_exception","reason":"action [cluster:monitor/main] is unauthorized for user [~hidden~]"}],"type":"security_exception","reason":"action [cluster:monitor/main] is unauthorized
```

**Comment by ppf2** [comment]
The error message reported is worse and more ambiguous if the user role is missing the `write` privilege for the index Logstash is writing to.  It simply throws an undefined method error instead of reporting the actual authorization issue. 

To reproduce, create a X-pack security user with just index and create_index privileges (but no `write` privilege).

```
[2016-12-28T18:41:00,773][ERROR][logstash.outputs.elasticsearch] Encountered an unexpected error submitting a bulk request! Will retry. {:error_message=>"undefined method `response' for #<LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError:0x50b5c209>", :class=>"NoMethodError", :backtrace=>["/Users/ppf2/Elastic/ElasticStack_5_1/5.1.1/logstash-5.1.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.4.1-java/lib/logstash/outputs/elasticsearch/common.rb:223:in `safe_bulk'", "/Users/ppf2/Elastic/ElasticStack_5_1/5.1.1/logstash-5.1.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.4.1-java/lib/logstash/outputs/elasticsearch/common.rb:109:in `submit'", "/Users/ppf2/Elastic/ElasticStack_5_1/5.1.1/logstash-5.1.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.4.1-java/lib/logstash/outputs/elasticsearch/common.rb:76:in `retrying_submit'", "/Users/ppf2/Elastic/ElasticStack_5_1/5.1.1/logstash-5.1.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.4.1-java/lib/logstash/outputs/elasticsearch/common.rb:27:in `multi_receive'", "/Users/ppf2/Elastic/ElasticStack_5_1/5.1.1/logstash-5.1.1/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:12:in `multi_receive'", "/Users/ppf2/Elastic/ElasticStack_5_1/5.1.1/logstash-5.1.1/logstash-core/lib/logstash/output_delegator.rb:42:in `multi_receive'", "/Users/ppf2/Elastic/ElasticStack_5_1/5.1.1/logstash-5.1.1/logstash-core/lib/logstash/pipeline.rb:331:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/Users/ppf2/Elastic/ElasticStack_5_1/5.1.1/logstash-5.1.1/logstash-core/lib/logstash/pipeline.rb:330:in `output_batch'", "/Users/ppf2/Elastic/ElasticStack_5_1/5.1.1/logstash-5.1.1/logstash-core/lib/logstash/pipeline.rb:288:in `worker_loop'", "/Users/ppf2/Elastic/ElasticStack_5_1/5.1.1/logstash-5.1.1/logstash-core/lib/logstash/pipeline.rb:258:in `start_workers'"]}
```

**Comment by jordansissel** [comment]
@roadrunner Your request "would be great if we can specify retryable error codes at input configuration" seems unrelated to what @ppf2 is describing. In order to avoid confusion, I recommend you open a separate issue about your concerns.

**Comment by jordansissel** [comment]
@ppf2 I wonder if a `403` should be considered not-retryable. It's a configuration problem the user could fix. Dropping feels like the wrong behavior.

As for the problem, I agree that the error messages you showed are missing important details.

**Comment by suyograo** [comment]
Fixed in https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/583
