### ISSUE TITLE
elasticsearch output fails on some inputs

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-elasticsearch#52]
migrated from https://logstash.jira.com/browse/LOGSTASH-2107

with this json, reading in from file, and outputting to elasticsearch:

```
{"message":"test","@version":"1","@timestamp":"2014-04-08T14:12:00.000+02:00","type":["cdn_access_log","ys-ssvod"],"tags":["cdn"],"host":"Casper-VAIO","path":"c:/Temp/Java/logstash/we_accesslog_apache","message_id":"mpJdW+Q8Q0xYv1Ha0bBNmB5LTps=","bytes-sent":32475,"object-size":32031,"bytes-recvd":356,"method":"GET","status":200,"time-recvd":"08/Apr/2014:14:12:00+0200","time-to-serve":1875}
(note that type was set by a mistake by a developer here - to an array 
However, instead of logstash completely halting reading of data.. I'd prefer it to log the line that breaks it, and continue.. it logs this:
{:timestamp=>"2014-04-09T10:02:42.456000+0200", :message=>"Failed to flush outgoing items", :outgoing_count=>1, :exception=>#<NameError: no method 'type' for arguments (org.jruby.RubyArray) on Java::OrgElasticsearchActionIndex::IndexRequest>, :backtrace=>["/usr/share/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:225:in `build_request'", "/usr/share/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:205:in `bulk'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:204:in `bulk'", "/usr/share/logstash/lib/logstash/outputs/elasticsearch.rb:331:in `flush'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1339:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216:in `buffer_flush'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1521:in `loop'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
```

**Comment by andrewvc** [comment]
I believe this is now fixed with the present retry logic. @talevy can you confirm?

**Comment by jordansissel** [comment]
Closing, idle.
