### ISSUE TITLE
ES hosts array: Support for parsing Environment Variables

### ISSUE THREAD

**Issue by berglh** [logstash-plugins/logstash-output-elasticsearch#520]
I am trying to use Environment Variables to configure the hosts item in the elasticsearch plugin. This is as per the document [Using Environment Variables in the Configuration](https://www.elastic.co/guide/en/logstash/current/environment-variables.html#_setting_the_tcp_port).

I'm guessing this behaviour is by design. I haven't tried this on any of the other parameters in the output plugin, I'm assuming it was decided that not reading environments would be something most people would not want to do [for the elasticsearch output plugin hosts field]. 

I am using containers and planning on scaling, so I'm designing my config to scale with simple changes to environment only. This would be useful to me; perhaps also to other architectures where the IP or hostnames of nodes might arbitrarily change and are read from a service discovery key value store on startup; like etcd.

- Version: 2.4.1 (Inside a Docker container)
- Operating System: OEL 7.2
- Config File (if you have sensitive info, please remove it):
```
output {
  if "[@metadata][ls-dev-mode]" == "false" {
    elasticsearch {
      hosts => [ "${ES_HOSTS}" ]
      index => "%{index}"
      flush_size => 1000
      workers => 16
      idle_flush_time => 30
    }
  }
}
```
 - Debug Log Output:
```
{:timestamp=>"2016-12-06T04:11:30.967000+0000", :message=>"Pipeline aborted due to error", :exception=>"LogStash::ConfigurationError", :error=>"Host '${ES_HOSTS}' was specified, but is not valid! Use either a full URL or a hostname:port string!", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:170:in `host_to_url'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:109:in `build_client'", "org/jruby/RubyArray.java:2414:in `map'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:109:in `build_client'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:20:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:44:in `build'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch.rb:134:in `build_client'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:14:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/output_delegator.rb:75:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:181:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:491:in `start_pipeline'"], :level=>:error, :file=>"logstash/agent.rb", :line=>"493", :method=>"start_pipeline"}
```

I also tried setting hosts to: `%{[@metadata][es-hosts]}` after adding a metadata field from the env; but I realised this would only populate with a JSON payload parsing through the pipeline which only starts after the ES plugin has been initialised; it was never going to work.

**Comment by jordansissel** [comment]
> I'm assuming it was decided that not reading environments would be something most people would not want to do.

I'm confused. In your previous sentence, you linked to the docs about using environment variables in Logstash, and then follow with a conclusion that "it was decided" to not read environment variables? I don't know what you are saying here; I am confused.

I'm not sure how to answer.

**Comment by jordansissel** [comment]
>  :error=>"Host '${ES_HOSTS}'

This happened because the `ES_HOSTS` environment variable is not set. 

I can reproduce this:

```
# Fails with similar error message:
% bin/logstash -e 'output { elasticsearch { hosts => "${ES_HOSTS}" } }'
Sending Logstash's logs to /home/jls/build/logstash-5.0.2/logs which is now configured via log4j2.properties
[2016-12-03T15:37:59,935][ERROR][logstash.agent           ] fetched an invalid config {:config=>"output { elasticsearch { hosts => \"${ES_HOSTS}\" } }input { stdin { type => stdin } }", :reason=>"Cannot evaluate `${ES_HOSTS}`. Environment variable `ES_HOSTS` is not set and there is no default value given."}

 # Works, because I provide the environment variable.
% ES_HOSTS="localhost:9200" bin/logstash -e 'output { elasticsearch { hosts => "${ES_HOSTS}" } }'
...
```

**Comment by berglh** [comment]
@jordansissel Cool; I rather to be wrong. It doesn't work in the same method for me. For what it's worth; I've also I am using an array of hosts; but even with a single host, I still must be doing something wrong:

```
user@server:/app/bin# export ES_HOSTS="1.2.3.4:9201"
user@server:/app/bin# echo $ES_HOSTS
1.2.3.4:9201
user@server:/app/bin# logstash -e 'output { elasticsearch { hosts => "${ES_HOSTS}" } }'Settings: Default pipeline workers: 56
Pipeline aborted due to error {:exception=>"LogStash::ConfigurationError", :error=>"Host '${ES_HOSTS}' was specified, but is not valid! Use either a full URL or a hostname:port string!", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:170:in `host_to_url'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:109:in `build_client'", "org/jruby/RubyArray.java:2414:in `map'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:109:in `build_client'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:20:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:44:in `build'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch.rb:134:in `build_client'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:14:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/output_delegator.rb:75:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:181:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:491:in `start_pipeline'"], :level=>:error}
stopping pipeline {:id=>"main"}
```

My versions:
user@server:/app/bin# logstash --version
logstash 2.4.1
user@server:/app/bin# logstash-plugin list --verbose logstash-output-elasticsearch
logstash-output-elasticsearch (2.7.1)
```

With your specific command:
```
root@freyja:/opt/logstash# ES_HOSTS="localhost:9200" bin/logstash -e 'output { elasticsearch { hosts => "${ES_HOSTS}" } }'
Settings: Default pipeline workers: 56
Pipeline aborted due to error {:exception=>"LogStash::ConfigurationError", :error=>"Host '${ES_HOSTS}' was specified, but is not valid! Use either a full URL or a hostname:port string!", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:170:in `host_to_url'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:109:in `build_client'", "org/jruby/RubyArray.java:2414:in `map'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:109:in `build_client'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:20:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:44:in `build'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch.rb:134:in `build_client'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:14:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/output_delegator.rb:75:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:181:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:491:in `start_pipeline'"], :level=>:error}
stopping pipeline {:id=>"main"}
```

**Comment by berglh** [comment]
Seems like this works fine in 5.0.2:
```
~/logstash-5.0.2$ ES_HOSTS="localhost:9200" bin/logstash -e 'output { elasticsearch { hosts => "${ES_HOSTS}" } }'

Sending Logstash's logs to /home/somebody/logstash-5.0.2/logs which is now configured via log4j2.properties
The stdin plugin is now waiting for input:
[2016-12-06T16:07:20,738][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>["http://localhost:9200"]}}
[2016-12-06T16:07:20,740][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
[2016-12-06T16:07:20,781][WARN ][logstash.outputs.elasticsearch] Marking url as dead. {:reason=>"Elasticsearch Unreachable: [http://localhost:9200][Manticore::SocketException] Connection refused (Connection refused)", :url=>#<URI::HTTP:0x41764dd8 URL:http://localhost:9200>, :error_message=>"Elasticsearch Unreachable: [http://localhost:9200][Manticore::SocketException] Connection refused (Connection refused)", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
```

**Comment by berglh** [comment]
But when I try to populate it with an array of hosts, it's still not very happy:
```
user@computer:~/logstash-5.0.2$ export ES_HOSTS="\"localhost:9200\", \"host2:9200\", \"host3:9200\""
user@computer:~/logstash-5.0.2$ echo $ES_HOSTS
"localhost:9200", "host2:9200", "host3:9200"
user@computer:~/logstash-5.0.2$ bin/logstash -e 'output { elasticsearch { hosts => [ "${ES_HOSTS}" ] } }'
Sending Logstash's logs to ~/logstash-5.0.2/logs which is now configured via log4j2.properties
The stdin plugin is now waiting for input:
[2016-12-06T16:17:02,070][ERROR][logstash.agent           ] Pipeline aborted due to error {:exception=>#<LogStash::ConfigurationError: Host '"localhost:9200", "host2:9200", "host3:9200"' was specified, but is not valid! Use either a full URL or a hostname:port string!>, :backtrace=>["~/logstash-5.0.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.2.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:183:in `host_to_url'", "~/logstash-5.0.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.2.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:93:in `build_pool'", "org/jruby/RubyArray.java:2414:in `map'", "~/logstash-5.0.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.2.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:93:in `build_pool'", "~/logstash-5.0.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.2.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:20:in `initialize'", "~/logstash-5.0.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.2.1-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:53:in `build'", "~/logstash-5.0.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.2.1-java/lib/logstash/outputs/elasticsearch.rb:188:in `build_client'", "~/logstash-5.0.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.2.1-java/lib/logstash/outputs/elasticsearch/common.rb:13:in `register'", "~/logstash-5.0.2/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:8:in `register'", "~/logstash-5.0.2/logstash-core/lib/logstash/output_delegator.rb:37:in `register'", "~/logstash-5.0.2/logstash-core/lib/logstash/pipeline.rb:196:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "~/logstash-5.0.2/logstash-core/lib/logstash/pipeline.rb:196:in `start_workers'", "~/logstash-5.0.2/logstash-core/lib/logstash/pipeline.rb:153:in `run'", "~/logstash-5.0.2/logstash-core/lib/logstash/agent.rb:250:in `start_pipeline'"]}
[2016-12-06T16:17:02,086][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2016-12-06T16:17:05,074][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}
user@computer:~/logstash-5.0.2$ bin/logstash -e 'output { elasticsearch { hosts => [ "localhost:9200", "host2:9200", "host3:9200" ] } }'
Sending Logstash's logs to ~/logstash-5.0.2/logs which is now configured via log4j2.properties
The stdin plugin is now waiting for input:
[2016-12-06T16:17:21,387][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>["http://localhost:9200", "http://host2:9200", "http://host3:9200"]}}
[2016-12-06T16:17:21,389][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
[2016-12-06T16:17:21,444][WARN ][logstash.outputs.elasticsearch] Marking url as dead. {:reason=>"Elasticsearch Unreachable: [http://localhost:9200][Manticore::SocketException] Connection refused (Connection refused)", :url=>#<URI::HTTP:0x51dd94f4 URL:http://localhost:9200>, :error_message=>"Elasticsearch Unreachable: [http://localhost:9200][Manticore::SocketException] Connection refused (Connection refused)", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
[2016-12-06T16:17:21,445][ERROR][logstash.outputs.elasticsearch] Failed to install template. {:message=>"Elasticsearch Unreachable: [http://localhost:9200][Manticore::SocketException] Connection refused (Connection refused)", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
[2016-12-06T16:17:21,446][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["localhost:9200", "host2:9200", "host3:9200"]}
[2016-12-06T16:17:21,447][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>1000}
[2016-12-06T16:17:21,449][INFO ][logstash.pipeline        ] Pipeline main started
[2016-12-06T16:17:21,467][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2016-12-06T16:17:26,390][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:url=>#<URI::HTTP:0x588852e4 URL:http://localhost:9200>, :healthcheck_path=>"/"}
^C[2016-12-06T16:17:29,147][WARN ][logstash.runner          ] SIGINT received. Shutting down the agent.
[2016-12-06T16:17:29,151][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}
```

**Comment by jordansissel** [comment]
Environment variables can only be strings at this time.

As a workaround, you can use m4, shell, sed, or similar tools to template your logstash configuration.

Here's an example to generate a config using m4:

```
% cat x.conf
output {
  elasticsearch {
    hosts => [ ES_HOSTS ]
    ...
  }
}

# Now using m4:
% m4 -DES_HOSTS='"host1:9200", "host2:9200", "host3:9200"' x.conf
output {
  elasticsearch {
    hosts => [ "host1:9200", "host2:9200", "host3:9200" ]
    ...
  }
}
```

**Comment by jordansissel** [comment]
It seems like this is leaning towards a feature request against Logstash, not a problem with the elasticsearch output.

**Comment by berglh** [comment]
@jordansissel Ok great. I had been replacing it in config with sed with the startup script. I saw this feature added and it expanded upon what I was using the logstash-filter-environment plugin. I figured I might be able to avoid using sed and just parse it in directly. Regardless; it seems I'm barking up the wrong tree. Sorry to waste your time.

**Comment by berglh** [comment]
Closing issue because it's not something that can be solved with this plugin.

**Comment by jordansissel** [comment]
This wasn't a waste :)

I think other folks have asked for this feature (lists in env).  I can't
find the ticket right now, but if you are interested, could you file an
issue on elastic/Logstash for this feature?

**Comment by jordanhenderson** [comment]
I was inclined to implement this to complete a sprint goal. If anyone is interested in the changes required, please see: https://github.com/jordanhenderson/logstash-output-elasticsearch/commit/c31e2a92163a381f9ba0a5fa98b73bf07597ae3d
Note: this is a temporary patch, and will become redundant once a logstash solution is possible. Until then, use at your own risk!
