### ISSUE TITLE
ES output failing with error messages

### ISSUE THREAD

**Issue by liujd** [logstash-plugins/logstash-output-elasticsearch#613]
- Version: logstash 5.4.1

- Operating System: CentOS

- Config File (if you have sensitive info, please remove it):
`
output {
  elasticsearch {
    hosts => "http://localhost:9200"
    index => "logstash-%{type}-%{+YYYY.MM.dd}"
    document_type => "%{type}"
  }
  stdout{codec => rubydebug}
}
`

- Steps to Reproduce:
[1] Run with the above config
[2] Wait until the message is processed
[3] Verify that you get the following error:
`
[2017-06-19T11:01:27,343][ERROR][logstash.pipeline        ] Error registering plugin {:plugin=>"#<LogStash::OutputDelegator:0x6768e439 @namespaced_metric=#<LogStash::Instrument::NamespacedMetric:0xf4b75de @metric=#<LogStash::Instrument::Metric:0x3a65c96a @collector=#<LogStash::Instrument::Collector:0x4096cca6 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x60ffb1a1 @store=#<Concurrent::Map:0x344ecde5 @default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x20f46c9f>, @fast_lookup=#<Concurrent::Map:0x567167db @default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs, :\"e2de397ae4a226cd942f13708ba4a863469c1872-3\"]>, @metric=#<LogStash::Instrument::NamespacedMetric:0x9fd6b6e @metric=#<LogStash::Instrument::Metric:0x3a65c96a @collector=#<LogStash::Instrument::Collector:0x4096cca6 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x60ffb1a1 @store=#<Concurrent::Map:0x344ecde5 @default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x20f46c9f>, @fast_lookup=#<Concurrent::Map:0x567167db @default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs]>, @logger=#<LogStash::Logging::Logger:0x577c8f63 @logger=#<Java::OrgApacheLoggingLog4jCore::Logger:0x78159c5a>>, @strategy=#<LogStash::OutputDelegatorStrategies::Shared:0xb28c507 @output=<LogStash::Outputs::ElasticSearch hosts=>[http://localhost:9200], index=>\"logstash-%{type}-%{+YYYY.MM.dd}\", document_type=>\"%{type}\", id=>\"e2de397ae4a226cd942f13708ba4a863469c1872-3\", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>\"plain_ddc6a9c7-85e7-4308-ab16-54c06991173b\", enable_metric=>true, charset=>\"UTF-8\">, workers=>1, manage_template=>true, template_name=>\"logstash\", template_overwrite=>false, idle_flush_time=>1, doc_as_upsert=>false, script_type=>\"inline\", script_lang=>\"painless\", script_var_name=>\"event\", scripted_upsert=>false, retry_initial_interval=>2, retry_max_interval=>64, retry_on_conflict=>1, action=>\"index\", ssl_certificate_verification=>true, sniffing=>false, sniffing_delay=>5, timeout=>60, pool_max=>1000, pool_max_per_route=>100, resurrect_delay=>5, validate_after_inactivity=>10000, http_compression=>false>>, @id=\"e2de397ae4a226cd942f13708ba4a863469c1872-3\", @metric_events=#<LogStash::Instrument::NamespacedMetric:0x724d7696 @metric=#<LogStash::Instrument::Metric:0x3a65c96a @collector=#<LogStash::Instrument::Collector:0x4096cca6 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x60ffb1a1 @store=#<Concurrent::Map:0x344ecde5 @default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x20f46c9f>, @fast_lookup=#<Concurrent::Map:0x567167db @default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs, :\"e2de397ae4a226cd942f13708ba4a863469c1872-3\", :events]>, @output_class=LogStash::Outputs::ElasticSearch>", :error=>"SSLConnectionSocketFactory not found in packages org.apache.http.client.methods, org.apache.http.client.entity, org.apache.http.client.config, org.apache.http.config, org.apache.http.conn.socket, org.apache.http.impl, org.apache.http.impl.client, org.apache.http.impl.conn, org.apache.http.impl.auth, org.apache.http.entity, org.apache.http.message, org.apache.http.params, org.apache.http.protocol, org.apache.http.auth, java.util.concurrent, org.apache.http.client.protocol, org.apache.http.conn.ssl, java.security.cert, java.security.spec, java.security, org.apache.http.client.utils; last error: cannot load Java class org.apache.http.client.utils.SSLConnectionSocketFactory"}
[2017-06-19T11:01:27,358][ERROR][logstash.agent           ] Pipeline aborted due to error {:exception=>#<NameError: SSLConnectionSocketFactory not found in packages org.apache.http.client.methods, org.apache.http.client.entity, org.apache.http.client.config, org.apache.http.config, org.apache.http.conn.socket, org.apache.http.impl, org.apache.http.impl.client, org.apache.http.impl.conn, org.apache.http.impl.auth, org.apache.http.entity, org.apache.http.message, org.apache.http.params, org.apache.http.protocol, org.apache.http.auth, java.util.concurrent, org.apache.http.client.protocol, org.apache.http.conn.ssl, java.security.cert, java.security.spec, java.security, org.apache.http.client.utils; last error: cannot load Java class org.apache.http.client.utils.SSLConnectionSocketFactory>, :backtrace=>["file:/home/calII/elk/logstash-5.4.1/vendor/jruby/lib/jruby.jar!/jruby/java/core_ext/module.rb:45:in `const_missing'", "/home/calII/elk/logstash-5.4.1/vendor/bundle/jruby/1.9/gems/manticore-0.6.1-java/lib/manticore/client.rb:603:in `ssl_socket_factory_from_options'", "/home/calII/elk/logstash-5.4.1/vendor/bundle/jruby/1.9/gems/manticore-0.6.1-java/lib/manticore/client.rb:394:in `pool_builder'", "/home/calII/elk/logstash-5.4.1/vendor/bundle/jruby/1.9/gems/manticore-0.6.1-java/lib/manticore/client.rb:402:in `pool'", "/home/calII/elk/logstash-5.4.1/vendor/bundle/jruby/1.9/gems/manticore-0.6.1-java/lib/manticore/client.rb:208:in `initialize'", "/home/calII/elk/logstash-5.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.1-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:26:in `initialize'", "/home/calII/elk/logstash-5.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:265:in `build_adapter'", "/home/calII/elk/logstash-5.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:269:in `build_pool'", "/home/calII/elk/logstash-5.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:60:in `initialize'", "/home/calII/elk/logstash-5.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.1-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:101:in `create_http_client'", "/home/calII/elk/logstash-5.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.1-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:97:in `build'", "/home/calII/elk/logstash-5.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.1-java/lib/logstash/outputs/elasticsearch.rb:230:in `build_client'", "/home/calII/elk/logstash-5.4.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.1-java/lib/logstash/outputs/elasticsearch/common.rb:23:in `register'", "/home/calII/elk/logstash-5.4.1/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:9:in `register'", "/home/calII/elk/logstash-5.4.1/logstash-core/lib/logstash/output_delegator.rb:41:in `register'", "/home/calII/elk/logstash-5.4.1/logstash-core/lib/logstash/pipeline.rb:268:in `register_plugin'", "/home/calII/elk/logstash-5.4.1/logstash-core/lib/logstash/pipeline.rb:279:in `register_plugins'", "org/jruby/RubyArray.java:1613:in `each'", "/home/calII/elk/logstash-5.4.1/logstash-core/lib/logstash/pipeline.rb:279:in `register_plugins'", "/home/calII/elk/logstash-5.4.1/logstash-core/lib/logstash/pipeline.rb:288:in `start_workers'", "/home/calII/elk/logstash-5.4.1/logstash-core/lib/logstash/pipeline.rb:214:in `run'", "/home/calII/elk/logstash-5.4.1/logstash-core/lib/logstash/agent.rb:398:in `start_pipeline'"]}`

How could i do ?

**Comment by jsvd** [comment]
which `java -version` ?

**Comment by liujd** [comment]
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by jordansissel** [comment]
Highlighting the main exception:

```
Pipeline aborted due to error {:exception=>#<NameError: SSLConnectionSocketFactory not found in packages org.apache.http.client.methods, org.apache.http.client.entity, org.apache.http.client.config, org.apache.http.config, org.apache.http.conn.socket, org.apache.http.impl, org.apache.http.impl.client, org.apache.http.impl.conn, org.apache.http.impl.auth, org.apache.http.entity, org.apache.http.message, org.apache.http.params, org.apache.http.protocol, org.apache.http.auth, java.util.concurrent, org.apache.http.client.protocol, org.apache.http.conn.ssl, java.security.cert, java.security.spec, java.security, org.apache.http.client.utils; last error: cannot load Java class org.apache.http.client.utils.SSLConnectionSocketFactory
```

**Comment by liujd** [comment]
@jordansissel 
I can't find Java class `org.apache.http.client.utils.SSLConnectionSocketFactory`

**Comment by liujd** [comment]
I try to add some jars to logstash-output-elasticsearch:
`httpclient-4.5.2.jar
log4j-1.2.17.jar`
And it wors.
Thanks for helpping.

**Comment by chenyanter** [comment]
how to add jars to logstash-output-elasticsearch, which path to add jars
I get the same issue
can you describe more detail about it
thanks for you
@liujd

**Comment by zoey0611** [comment]
I am getting this same error when i run logstash. It isn't able to find org.apache.http.client.utils.SSLConnectionSocketFactory and so it errors out. 
How did this get fixed ?

**Comment by pkgajulapalli** [comment]
@chenyanter Try adding the jars to `LOGSTASH_HOME/vendor/jruby/lib/` folder.

**Comment by djkr2** [comment]
where to add the jar you have suggested,because "logstash-output-elasticsearch" i'm not getting. 
httpclient-4.5.2.jar log4j-1.2.17.jar
@liujd
