### ISSUE TITLE
Retry and DLQ issues

### ISSUE THREAD

**Issue by dropje86** [logstash-plugins/logstash-output-elasticsearch#630]
After building my own plugin (v7.3.8) with custom RETRYABLE_CODES and DLQ_CODES configured I ran into multiple issues during testing.

In `lib/logstash/outputs/elasticsearch/common.rb`: 
```ruby
if RETRYABLE_CODES.include?(e.response_code)
    log_hash = {:code => e.response_code, :url => e.url.sanitized.to_s}
```
I get failures (at least) with a 502 response as the `sanitized` method does not exist on the response url object. This will lead to a catchall retry mechanism kicking in but throws exceptions.

Other issue I found is with a 404 response code and DLQ. In: `lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb` a 404 is excluded from throwing an exception due to possible template installation failure. Problem is that because `BadResponseCodeError` is not thrown, the Retry and DLQ logic is abandoned due to an exception being thrown in the `join_bulk_responses()`, which fails on parsing the response body.

Here a snippet of that exception:
```
[2017-08-01T21:42:01,126][ERROR][logstash.outputs.elasticsearch] An unknown error occurred sending a bulk request to Elasticsearch. We will retry indefinitely {:error_message=>"undefined method `[]' for nil:NilClass", :error_class=>"NoMethodError", :backtrace=>["/usr/share/logstash/vendor/local_gems/c95b210f/logstash-output-elasticsearch-7.3.8-java/lib/logstash/outputs/elasticsearch/http_client.rb:131:in `join_bulk_responses'", "org/jruby/RubyEnumerable.java:1456:in `any?'", "/usr/share/logstash/vendor/local_gems/c95b210f/logstash-output-elasticsearch-7.3.8-java/lib/logstash/outputs/elasticsearch/http_client.rb:130:in `join_bulk_responses'", "/usr/share/logstash/vendor/local_gems/c95b210f/logstash-output-elasticsearch-7.3.8-java/lib/logstash/outputs/elasticsearch/http_client.rb:126:in `bulk'"
```

**Comment by andrewvc** [comment]
I have a partial fix in #637 , looking into the 404 issue now.

**Comment by andrewvc** [comment]
I'm not sure that the 404 issue is a bug. There is no circumstance I can imagine in which the `_bulk` endpoint should return a 404. How is that happening on your end?

**Comment by dropje86** [comment]
@andrewvc When you have a reverse proxy in between, in my case a dynamic one (Fabiolb) which returns a 404 when no route is found (due to cluster being down in Consul service Discovery).

**Comment by andrewvc** [comment]
@dropje86 I think the 404 behavior change is fine, but shouldn't Fabiolb be returning a 503? 404 in that case seems wrong to me.

**Comment by dropje86** [comment]
@andrewvc Yeah that might be valid I'm not sure tbh. The reason Fabio does that by default is because it received a request for an unknown route / endpoint, which kind of makes sense too. It is resolvable by customizing the error code in Fabio when a route is not found so if you guys think a 404 shouldn't be retried I'll do that.

**Comment by andrewvc** [comment]
That's a good point WRT auto-create being false.  At any rate, 404s are now DLQed. I'm going to close this one :)

Thanks for all the great feedback @dropje86 !
