### ISSUE TITLE
to_s in the wrong place

### ISSUE THREAD

**Issue by mcandre** [logstash-plugins/logstash-output-elasticsearch#662]
The https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/f3c4895897cb93303fe58132ff186ea8dbb0c465 patch to fix a URl sanitization error may have applied the `to_s` too late in the method call chain. Instead of doing `.sanitized.to_s`, we should probably do `.to_s.sanitized`, no?

Weird that the unit tests didn't catch this one.

**Comment by aegixx** [comment]
This is incorrect, since String doesn't implement a `sanitized` method.  

Instead, I think we have a bad test here - the url passed into creating a `BadResponseCodeError` is never a `SafeUri` (which is where `sanitized` is implemented.  

https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/ed5952d3ce1a010ed95423bcac20f9a6ef8e4818/lib/logstash/outputs/elasticsearch/http_client.rb#L147 raises a `BadResponseCodeError` by passing `@bulk_path`

https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/ed5952d3ce1a010ed95423bcac20f9a6ef8e4818/lib/logstash/outputs/elasticsearch/http_client/pool.rb#L38 shows that `@bulk_path` is a string by default. (And so does the documentation: https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-bulk_path)

Yet `ManticoreAdapter` spec passes a `SafeUri` object: https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/5b1e53def85b60d5fb04f38f7a5620744e7425ab/spec/unit/outputs/elasticsearch/http_client/manticore_adapter_spec.rb#L48
which passes - but only for the test itself.

**Comment by aegixx** [comment]
It looks like even the `ManticoreAdapter` converts it to a string before sending:
https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb#L69

**Comment by mcandre** [comment]
@aegixx sanitized is monkeypatched into String, it's Ruby.

**Comment by aegixx** [comment]
`sanitize` is an ActionView helper (http://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-sanitize) but I'm not aware of any built-in `sanitized` method.  Can you point out where this method has been monkeypatched in?  I wasn't able to locate any reference to it beyond the implementation in `SafeURI`

**Comment by andrewvc** [comment]
Have you experienced an error here? I assume you got a stack trace leading back to https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/f3c4895897cb93303fe58132ff186ea8dbb0c465#diff-80f5e58dec942267dcee4b6f182bdfcfR250 ?

There's some confusion here, we don't use `ActionView`, the intended method is [this one](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/util/safe_uri.rb#L40) in `SafeURI`.

**Comment by jsvd** [comment]
commit https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/5b1e53def85b60d5fb04f38f7a5620744e7425ab must be backported to 7.x, in certain situations can cause the plugin to crash. see more on https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/637#issuecomment-330187367

**Comment by CelsoSantos** [comment]
I too am facing this error on Logstash 5.6.2.

However, I did come to notice this only happens when Logstash/X-Pack monitoring is enabled.

**Comment by falcorocks** [comment]
@CelsoSantos can you explain to me how to disable that setting? I have tried to add a line to logstash.yml with
`xpack.monitoring.enabled: false`

but then logstash throws an error
```
Sending Logstash's logs to /usr/local/Cellar/logstash/5.6.2/libexec/logs which is now configured via log4j2.properties
[2017-10-26T12:27:52,915][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/usr/local/Cellar/logstash/5.6.2/libexec/modules/fb_apache/configuration"}
[2017-10-26T12:27:52,919][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/usr/local/Cellar/logstash/5.6.2/libexec/modules/netflow/configuration"}
[2017-10-26T12:27:52,927][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "xpack.monitoring.enabled" hasn't been registered>, :backtrace=>["/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/settings.rb:32:in `get_setting'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/settings.rb:64:in `set_value'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/settings.rb:83:in `merge'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/settings.rb:83:in `merge'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/settings.rb:135:in `validate_all'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/runner.rb:243:in `execute'", "/usr/local/Cellar/logstash/5.6.2/libexec/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/local/Cellar/logstash/5.6.2/libexec/logstash-core/lib/logstash/runner.rb:204:in `run'", "/usr/local/Cellar/logstash/5.6.2/libexec/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/local/Cellar/logstash/5.6.2/libexec/lib/bootstrap/environment.rb:71:in `(root)'"]}
```

Should I add that line also in elasticsearch.yml and kibana.yml

**Comment by CelsoSantos** [comment]
@falcorocks To me it looks like you don't have x-pack installed or at least not properly registered.
Have you tried to (re)install x-pack?

**Comment by andrewherron** [comment]
I'm getting this error as well now. LS version 6.1.1 and plugin version 9.0.2.

**Comment by andrewherron** [comment]
Investigated this further, the original problem was a 404 on my side, but when it sends the exception it tries to do:

        log_hash = {:code => e.response_code, :url => e.url.sanitized.to_s}

This throws an error since there's no "sanitized" method for e.url. When I removed the sanitized from the chain I was able to see my actual error and correct it.
