### ISSUE TITLE
Misleading log entries when there is a connection issue with the underlying ES cluster

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-elasticsearch#774]
Tested on 6.2.1.

If you define a ES cluster that is not available, or have a host name that is not reachable, the Logstash log ends up filling with various misleading and confusing log messages like the following:

```
[2018-05-21T12:01:03,664][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://elastic:xxxxxx@elk1:9200/]}}
[2018-05-21T12:01:03,685][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>https://elastic:xxxxxx@elk1:9200/, :path=>"/"}
[2018-05-21T12:01:03,880][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://elastic:xxxxxx@elk1:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [https://elastic:xxxxxx@elk1:9200/][Manticore::ResolutionFailure] elk1: nodename nor servname provided, or not known"}
[2018-05-21T12:01:03,891][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
[2018-05-21T12:01:03,908][ERROR][logstash.outputs.elasticsearch] Failed to install template. {:message=>"Template file '' could not be found!", :class=>"ArgumentError", :backtrace=>["/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.3-java/lib/logstash/outputs/elasticsearch/template_manager.rb:31:in `read_template_file'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.3-java/lib/logstash/outputs/elasticsearch/template_manager.rb:17:in `get_template'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.3-java/lib/logstash/outputs/elasticsearch/template_manager.rb:7:in `install_template'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.3-java/lib/logstash/outputs/elasticsearch/common.rb:57:in `install_template'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.3-java/lib/logstash/outputs/elasticsearch/common.rb:26:in `register'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:9:in `register'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/logstash-core/lib/logstash/output_delegator.rb:42:in `register'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/logstash-core/lib/logstash/pipeline.rb:341:in `register_plugin'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/logstash-core/lib/logstash/pipeline.rb:352:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/logstash-core/lib/logstash/pipeline.rb:352:in `register_plugins'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/logstash-core/lib/logstash/pipeline.rb:735:in `maybe_setup_out_plugins'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/logstash-core/lib/logstash/pipeline.rb:362:in `start_workers'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/logstash-core/lib/logstash/pipeline.rb:289:in `run'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/logstash-core/lib/logstash/pipeline.rb:249:in `block in start'"]}
[2018-05-21T12:01:03,915][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["https://elk1:9200"]}
[2018-05-21T12:01:04,311][INFO ][logstash.pipeline        ] Pipeline started succesfully {:pipeline_id=>"main", :thread=>"#<Thread:0x67b70258 sleep>"}
[2018-05-21T12:01:04,395][INFO ][logstash.agent           ] Pipelines running {:count=>1, :pipelines=>["main"]}
[2018-05-21T12:01:05,134][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `<' for nil:NilClass>, :backtrace=>["/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.3-java/lib/logstash/outputs/elasticsearch/common.rb:213:in `get_event_type'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.3-java/lib/logstash/outputs/elasticsearch/common.rb:165:in `event_action_params'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.3-java/lib/logstash/outputs/elasticsearch/common.rb:39:in `event_action_tuple'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.3-java/lib/logstash/outputs/elasticsearch/common.rb:34:in `block in multi_receive'", "org/jruby/RubyArray.java:2486:in `map'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.0.3-java/lib/logstash/outputs/elasticsearch/common.rb:34:in `multi_receive'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:13:in `multi_receive'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/logstash-core/lib/logstash/output_delegator.rb:49:in `multi_receive'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/logstash-core/lib/logstash/pipeline.rb:479:in `block in output_batch'", "org/jruby/RubyHash.java:1343:in `each'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/logstash-core/lib/logstash/pipeline.rb:478:in `output_batch'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/logstash-core/lib/logstash/pipeline.rb:430:in `worker_loop'", "/Users/my_user/Elastic/ElasticStack_6_0/6.2.1/logstash-6.2.1/logstash-core/lib/logstash/pipeline.rb:385:in `block in start_workers'"]}
[2018-05-21T12:01:05,290][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: org.jruby.exceptions.RaiseException: (SystemExit) exit
```

While it does have a message that indicates the host being unreachable, it also generates various misleading ERROR and FATAL entries indicating that the template cannot be installed, and that is exited due to an NoMethodError issue.

Ideally, we will want to suppress the other messages that are a side effect/result of the ES cluster not being reachable.  Or have the ERROR/FATAL messages indicate the exact cause (instead of simply having the unreachable messages as an INFO/WARN level entry).

**Comment by robbavey** [comment]
@ppf2 [Changes](#758) were recently made that should improve the experience when ES is down during Logstash startup. The changes are in version `9.1.3` of the plugin onwards.

**Comment by ppf2** [comment]
Awesome thx!
