### ISSUE TITLE
create action does not use _id for request

### ISSUE THREAD

**Issue by pickypg** [logstash-plugins/logstash-output-elasticsearch#79]
Running Logstash 1.5RC2.

Input file (`file.json`):

```json
{"type":"test","_id":"ab66c2e6-e641-457c-aa49-7ad87ba680eb","other":"value"}
```

Logstash conf (`json.conf`):

```ruby
input {
  stdin {
    codec => json { }
  }
}

output {
  elasticsearch {
    action => "create"
    host => ["localhost"]
    index => "test-%{+YYYY.MM.dd}"
    protocol => "http"
  }
  stdout {
    codec => rubydebug
  }
}
```

Command:

```bash
$ cat file.json | bin/logstash -f json.conf
```

Output from Elasticsearch 1.4.4 (emphasis on the `Caused by`):

```
[2015-03-19 23:34:10,203][DEBUG][action.bulk              ] [Meggan] [test-2015.03.20][0] failed to execute bulk item (index) index {[test-2015.03.20][test][AUw1PswAB7p1lmy3zZZY], source[{"type":"test","_id":"ab66c2e6-e641-457c-aa49-7ad87ba680eb","other":"value","@version":"1","@timestamp":"2015-03-20T03:34:09.164Z","host":"Chriss-MBP-2"}]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [_id]
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:416)
	at org.elasticsearch.index.mapper.internal.IdFieldMapper.parse(IdFieldMapper.java:295)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:709)
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:500)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:542)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:491)
	at org.elasticsearch.index.shard.service.InternalIndexShard.prepareCreate(InternalIndexShard.java:392)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:444)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:150)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:512)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Provided id [AUw1PswAB7p1lmy3zZZY] does not match the content one [ab66c2e6-e641-457c-aa49-7ad87ba680eb]
	at org.elasticsearch.index.mapper.internal.IdFieldMapper.parseCreateField(IdFieldMapper.java:310)
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:406)
	... 13 more
```

Output on the command line for Logstash:

```
{
          "type" => "test",
           "_id" => "ab66c2e6-e641-457c-aa49-7ad87ba680eb",
         "other" => "value",
      "@version" => "1",
    "@timestamp" => "2015-03-20T03:34:09.164Z",
          "host" => "Chriss-MBP-2"
}
failed action with response of , dropping action: ["create", {:_id=>nil, :_index=>"test-2015.03.20", :_type=>"test"}, #<LogStash::Event:0x575fcc7d @metadata_accessors=#<LogStash::Util::Accessors:0x14adb7d3 @store={"retry_count"=>0}, @lut={}>, @cancelled=false, @logger=#<Cabin::Channel:0x2baec2f8 @metrics=#<Cabin::Metrics:0x2bbcfd4 @metrics_lock=#<Mutex:0x7bd1e37f>, @metrics={}, @channel=#<Cabin::Channel:0x2baec2f8 ...>>, @subscriber_lock=#<Mutex:0x7b4100e6>, @level=:warn, @subscribers={15592=>#<Cabin::Outputs::IO:0x7abc0a0b @io=#<IO:fd 1>, @lock=#<Mutex:0xe02d438>>}, @data={}>, @data={"type"=>"test", "_id"=>"ab66c2e6-e641-457c-aa49-7ad87ba680eb", "other"=>"value", "@version"=>"1", "@timestamp"=>"2015-03-20T03:34:09.164Z", "host"=>"Chriss-MBP-2"}, @metadata={"retry_count"=>0}, @accessors=#<LogStash::Util::Accessors:0x76babee8 @store={"type"=>"test", "_id"=>"ab66c2e6-e641-457c-aa49-7ad87ba680eb", "other"=>"value", "@version"=>"1", "@timestamp"=>"2015-03-20T03:34:09.164Z", "host"=>"Chriss-MBP-2"}, @lut={"host"=>[{"type"=>"test", "_id"=>"ab66c2e6-e641-457c-aa49-7ad87ba680eb", "other"=>"value", "@version"=>"1", "@timestamp"=>"2015-03-20T03:34:09.164Z", "host"=>"Chriss-MBP-2"}, "host"], "type"=>[{"type"=>"test", "_id"=>"ab66c2e6-e641-457c-aa49-7ad87ba680eb", "other"=>"value", "@version"=>"1", "@timestamp"=>"2015-03-20T03:34:09.164Z", "host"=>"Chriss-MBP-2"}, "type"]}>>] {:level=>:warn}
```

**Comment by talevy** [comment]
just a quick glance, I see that the action's `:id` field is generated by extracting a field from the event, and you must specify which field to grab this from using the `document_id` config option.

```
output {
  elasticsearch {
    ...
    document_id => "%{_id}"
    ...
  }
}
```

***[reference lines](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch.rb#L401-L402)

**Comment by pickypg** [comment]
@talevy Interesting, that definitely appears to fix the problem. I didn't notice that the _id was effectively overwritten here: https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/25aebfe5779d14396efd8720429ed16191342dd1/lib/logstash/outputs/elasticsearch.rb#L402

**Comment by pickypg** [comment]
As a head's up for anyone coming across this, this is also true of Logstash 1.4.2.
