### ISSUE TITLE
Logstash losing connection to Elasticsearch nodes

### ISSUE THREAD

**Issue by nickpeirson** [logstash-plugins/logstash-output-elasticsearch#793]
We're seeing errors in the logstash logs where logstash is marking an elasticsearch node as dead, e.g.:
```
[2018-08-23T07:20:11,108][WARN ][logstash.outputs.elasticsearch] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://elasticsearch3:9200/][Manticore::SocketException] Connection reset {:url=>http://elasticsearch3:9200/, :error_message=>"Elasticsearch Unreachable: [http://elasticsearch3:9200/][Manticore::SocketException] Connection reset", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
```
This is quickly followed by a health check that marks it as healthy. The frequency of these seem to increase the longer that logstash is running. Eventually we stop getting logs in elasticsearch. Restarting logstash causes logs to start being indexed again. We have two logstash instances on two servers. While one has stopped sending logs, the other can continue to send logs. To me this indicates that the problem is within logstash rather than within elasticsearch.

I produced a packet capture (`sudo tcpdump -i enp0s31f6 -s 65535 -w logstash.pcap 'port 9200'`) while we were seeing the error. In the packet capture I can see elasticsearch respond with a 400 error:

    HTTP/1.0 400 Bad Request
    content-type: application/json; charset=UTF-8
    content-length: 203
    
    {
      "error": {
        "root_cause": [
          {
            "type": "illegal_argument_exception",
            "reason": "text is empty (possibly HTTP/0.9)"
          }
        ],
        "type": "illegal_argument_exception",
        "reason": "text is empty (possibly HTTP/0.9)"
      },
      "status": 400
    }

I then see 5 TCP RST packets from elasticsearch to logstash. The last RST packet was at `07:20:11.107663`, which matches the time of the logstash error, `07:20:11,108`.

I'm finding the packet capture a little confusing. I've filtered the packet capture down to the IPs of the logstash and ES server in question, and to the ports where we see the 400 and RSTs, however prior to the 400 there appears to be a `_bulk` request in progress, then a 414 response during the request in the middle of the `_bulk` request, then the `_bulk` request continues, then we get the 400:

**Logstash -> ES**

    POST /_bulk HTTP/1.1
    Connection: Keep-Alive
    Content-Type: application/json
    Content-Length: 167481062
    Host: elasticsearch3:9200
    User-Agent: Manticore 0.6.1
    Accept-Encoding: gzip,deflate
    { ... data ... }

**ES -> Logstash**

    HTTP/1.1 413 Request Entity Too Large
    content-length: 0

**Logstash -> ES**

    { ... data continues ... }

**ES -> Logstash**

    HTTP/1.0 400 Bad Request
    content-type: application/json; charset=UTF-8
    content-length: 203
    {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"text is empty (possibly HTTP/0.9)"}],"type":"illegal_argument_exception","reason":"text is empty (possibly HTTP/0.9)"},"status":400}

We're running Logstash 6.0.1 on Ubuntu 18.04.1.
**logstash.yml**
```
path.data: /var/lib/logstash
path.config: /etc/logstash/conf.d/*.conf
path.logs: /var/log/logstash
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.url: ["elasticsearch2:9200", "elasticsearch3:9200", "elasticsearch1:9200", "elasticsearch4:9200", "elasticsearch5:9200", "elasticsearch6:9200"]
xpack.management.enabled: false
```
**logstash.conf**
```
input {
  redis {
    codec => "json"
    data_type => "pattern_channel"
    host => "127.0.0.1"
    port => 6379
    key => "logstash.*"
    id => "redis_1"
    tags => ["ISP1"]
  }
  redis {
    codec => "json"
    data_type => "pattern_channel"
    host => "127.0.0.1"
    port => 6380
    key => "logstash.*"
    id => "redis_2"
    tags => ["ISP2"]
  }
}

filter {
  mutate {
    add_field => {
      receivedAt => "%{+yyyy-MM-dd HH:mm:ss.SSSZ}"
      isp => "%{[tags][0]}"
    }
    remove_field => tags
    convert => {
      order => "string"
      product => "string"
    }
    id => "convert_order_and_product"
  }

  date {
    match => ["timestamp", "UNIX"]
    remove_field => ["timestamp"]
    id => "add_timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch2:9200","elasticsearch3:9200","elasticsearch1:9200","elasticsearch4:9200","elasticsearch5:9200","elasticsearch6:9200"]
    id => "elasticsearch_logging_cluster"
  }
}
```

**Comment by nickpeirson** [comment]
Hi @jsvd, we're still seeing this on a daily basis. Let me know if there's any further information I can provide to help diagnose the issue.

**Comment by snblitz** [comment]
I too am experiencing this issue.  ES 6.4.1.  It happens daily two to four times.  I have 3 bare metal servers with the ELK components in docker containers running network = host.   I am processing about 7000 documents per minute ingesting 24 hours per day.  The logstash pipeline has three elasticsearch instances it can talk to on different hosts.  Even so it loses data during these "outages".
I have noticed that the JVM heap usage gets to 96% but I do not know if this is correlated with the issue.

**Comment by snblitz** [comment]
Here is the issue as seen in the logstash log (there is no corresponding reported by the elasticsearch instance, the es log is clean at the time)

```
[2018-10-19T14:01:04,694][WARN ][logstash.outputs.elasticsearch] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://192.154.107.18:9200/][Manticore::SocketTimeout] Read timed out {:url=>http://192.154.107.18:9200/, :error_message=>"Elasticsearch Unreachable: [http://192.154.107.18:9200/][Manticore::SocketTimeout] Read timed out", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
[2018-10-19T14:01:04,694][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch' but Elasticsearch appears to be unreachable or down! {:error_message=>"Elasticsearch Unreachable: [http://192.154.107.18:9200/][Manticore::SocketTimeout] Read timed out", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError", :will_retry_in_seconds=>2}
[2018-10-19T14:01:05,248][WARN ][logstash.outputs.elasticsearch] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketTimeout] Read timed out {:url=>http://localhost:9200/, :error_message=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketTimeout] Read timed out", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
[2018-10-19T14:01:05,248][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch' but Elasticsearch appears to be unreachable or down! {:error_message=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketTimeout] Read timed out", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError", :will_retry_in_seconds=>2}
[2018-10-19T14:01:05,558][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
[2018-10-19T14:01:05,560][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2018-10-19T14:01:08,514][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://192.154.107.18:9200/, :path=>"/"}
[2018-10-19T14:01:08,516][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://192.154.107.18:9200/"}
[2018-10-19T14:01:49,629][WARN ][logstash.outputs.elasticsearch] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketTimeout] Read timed out {:url=>http://localhost:9200/, :error_message=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketTimeout] Read timed out", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}


```

**Comment by solshark** [comment]
For me issue disappeared after adding ```sniffing => false``` to output elasticsearch section in logstash.conf:

```
output {
  elasticsearch {
      hosts => ["elasticsearch:9200"]
      sniffing => false
      index => "mycoolindex-%{+YYYY.MM.dd}"
    }
}
```

**Comment by SorJEF** [comment]
I had the same issue. In my case, elasticsearch was running behind nginx proxy. Nginx used default [`client_max_body_size`](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) value which is 1mb. 

I've changed nginx max body size ([this post was very helpful](https://stackoverflow.com/a/14358928/1044637)) to be the same as the [`http.max_content_length`](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html) in elasticsearch (100mb by default) and now everything works as expected.

P.S. @solshark, it seems your approach only masks the problem. There is a high chance the issue persists with `sniffing` turned off, but logstash just does not show that the communication was interrupted.

**Comment by crossan007** [comment]
I seem to be getting this same issue, and it consistently starts 2-3 minutes after starting logstash. (although I'm on an older version of logstash - `logstash-5.6.16`) 

Once the errors begin flooding the log, no more events are written to ES.

`sniffing => false` does not prevent the errors from appearing for me.

I've tried both disabling(`-1`) and lengthening (`30s`) my ES refresh interval, to no effect (thinking maybe there's resource contention occurring with a Lucene index refresh).
```
PUT /*/_settings
{
    "index" : {
        "refresh_interval" : "30s"
    }
}
```

**Comment by crossan007** [comment]
Looks like this GitHub issue was created based on feedback from the ES forums: https://discuss.elastic.co/t/logstash-losing-connection-to-elasticsearch-nodes/145544/3

**Comment by crossan007** [comment]
I discovered the cause of my issue: some applications were "misbehaving", creating log entries that were in the 10's of MB.

These *large* events were flowing _into_ Logstash seemingly fine, but were likely saturating the connection pool to Elasticsearch, thereby causing my problems.

Sharing some of my observations and keywords in case anyone else encounters similar.

The initial "problem" I noticed were lots of `Connection Reset` in my Logstash logs:
```
[2019-05-20T00:00:38,388][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch' but Elasticsearch appears to be unreachable or down! {:error_message=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connection reset", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError", :will_retry_in_seconds=>64}
```

Seeing that there were problems in the connection between LS and ES, I made a few shot-in-the-dark attempts at changing the `Elasticsearch Output` plugin parameters in Logstash (ultimately to no avail), which I'll be reverting:
```
timeout => 120
pool_max => 10
pool_max_per_route => 10
validate_after_inactivity => 750
```

Whilst stopping logstash, I saw a bunch of messages resembling this:
```
[2019-05-21T07:58:31,020][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>500, "stalling_thread_info"=>{["LogStash::Filters::Age", {"id"=>"8ab19d239cd73e736c66ef2f20540216cf61eae1-38"}]=>[{"thread_id"=>49, "name"=>"[main]>worker0", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.23/lib/stud/interval.rb:89:in `sleep'"}, {"thread_id"=>50, "name"=>"[main]>worker1", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.23/lib/stud/interval.rb:89:in `sleep'"}, {"thread_id"=>51, "name"=>"[main]>worker2", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.23/lib/stud/interval.rb:89:in `sleep'"}, {"thread_id"=>52, "name"=>"[main]>worker3", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.23/lib/stud/interval.rb:89:in `sleep'"}]}}
```

I thought it very odd that the `Age` plugin would stall and take too long to stop; this was not my "aha" moment, but in hindsight makes sense.

The "smoking gun" appeared when I ran TCPdump to inspect the traffic between LS and ES `tcpdump -i any -nn host 127.0.0.1 -A`, and noticed a majority of the HTTP index request payloads contained LOTS of `null` characters.

This reminded me of an issue I encountered a few weeks ago where a misbehaving application was creating 300+MB log _events_.  In this previous circumstance, the events were egregiously large, and ultimately failed to be ingested by the logstash beats input plugin; however, *this time*, the events were under the input plugin's failure threshold, so LS happily accepted the events.

My solution was to add some length filtering logic at the beginning of my `filebeat` logstash configuration:
```
ruby {
      code => "
                if (event.get('message'))
                  event.set('message_length', event.get('message').length)
                end
              "
    }

    truncate {
      fields => ["message"]
      length_bytes => 100000
    }

    if [message_length] and [message_length] > 100000  {
      mutate {
        add_tag => [ "truncated" ]
      }
    }

```

This may not be the most elegant solution, but seems to work for now.

The `add_tag` option in the `truncate` plugin seems to misbehave (https://github.com/logstash-plugins/logstash-filter-truncate/issues/4) so I wrote my own logic for "tagging" events which were subject to truncation, along with persisting the *original* size of the event to ES.

**Comment by rkgurram** [comment]
We have faced the same issue and after much debugging realized that the logstash configuration was in error, specifically the pipeline.workers configuration was wrong. We have tried to document the same in this post https://medium.com/@rkgurram/tuning-logstash-as-elastic-search-becomes-not-reachable-bd2365850714

**Comment by MakoWish** [comment]
I am seeing the same issue, but I have a feeling it is related to latency for me. I am trying to find if there is a setting to increase the timeout period to test. Anybody?

In my case, auditbeat instances in our Australia office kept dropping the connection to one of our local (California) logstash servers. I thought I would spin up a Logstash server in Australia and have that send the data to our Elastic cluster here. Unfortunately, now the Logstash server is giving these "Manticore::SocketTimeout] Read timed out", and the auditbeat agent is still showing the connection drops; just to the new Australia Logstash instance instead. 

Auditbeat log errors:
```
2019-07-31T06:10:36.692+1000	ERROR	logstash/async.go:256	Failed to publish events caused by: write tcp 1.2.3.4:64455->123.45.67.89:5044: wsasend: An existing connection was forcibly closed by the remote host.
2019-07-31T06:10:37.823+1000	ERROR	pipeline/output.go:121	Failed to publish events: write tcp 1.2.3.4:64455->123.45.67.89:5044: wsasend: An existing connection was forcibly closed by the remote host.
2019-07-31T06:10:37.823+1000	INFO	pipeline/output.go:95	Connecting to backoff(async(tcp://AustraliaLogstash.foo.bar:5044))
2019-07-31T06:10:37.825+1000	INFO	pipeline/output.go:105	Connection to backoff(async(tcp://AustraliaLogstash.foo.bar:5044)) established
```

Logstash errors:
```
Jul 30 20:10:04 AustraliaLogstash logstash[8237]: [2019-07-30T20:10:04,927][WARN ][logstash.outputs.elasticsearch] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://ES03.foo.bar:9200/][Manticore::SocketTimeout] Read timed out {:url=>http://ES03.foo.bar:9200/, :error_message=>"Elasticsearch Unreachable: [http://ES03.foo.bar:9200/][Manticore::SocketTimeout] Read timed out", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
Jul 30 20:10:04 AustraliaLogstash logstash[8237]: [2019-07-30T20:10:04,937][WARN ][logstash.outputs.elasticsearch] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://ES05.foo.bar:9200/][Manticore::SocketTimeout] Read timed out {:url=>http://ES05.foo.bar:9200/, :error_message=>"Elasticsearch Unreachable: [http://ES05.foo.bar:9200/][Manticore::SocketTimeout] Read timed out", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
Jul 30 20:10:04 AustraliaLogstash logstash[8237]: [2019-07-30T20:10:04,951][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch' but Elasticsearch appears to be unreachable or down! {:error_message=>"Elasticsearch Unreachable: [http://ES03.foo.bar:9200/][Manticore::SocketTimeout] Read timed out", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError", :will_retry_in_seconds=>2}
Jul 30 20:10:04 AustraliaLogstash logstash[8237]: [2019-07-30T20:10:04,951][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch' but Elasticsearch appears to be unreachable or down! {:error_message=>"Elasticsearch Unreachable: [http://ES05.foo.bar:9200/][Manticore::SocketTimeout] Read timed out", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError", :will_retry_in_seconds=>2}
Jul 30 20:10:06 AustraliaLogstash logstash[8237]: [2019-07-30T20:10:06,202][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://ES03.foo.bar:9200/"}
Jul 30 20:10:06 AustraliaLogstash logstash[8237]: [2019-07-30T20:10:06,726][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://ES05.foo.bar:9200/"}
```

These errors repeat until the auditbeat instance eventually crashes. 

Would love some ideas on what we could do to troubleshoot.

**Comment by pedroborba789** [comment]
I was having the same issue, after inspecting the data that was sent to the elasticsearch, realized it was bigger than the default http.max_content_length(100mb) of the elasticsearch.

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html

Hope it helps someone. :)

**Comment by lpkirby** [comment]
@pedroborba789 Thank you so much!  I've been dealing with this issue for weeks and finally ran across your post here.  It fixed my problem.  I wish elasticsearch logged those drops due to content length.

For anyone else reading this, along with adjusting http.max_content_length, you might be able to adjust the `pipeline.batch.size` in logstash.

**Comment by crossan007** [comment]
An additional note here:

If you have events stuck in a logstash persistent disk-backed queue that will not post into elasticsearch because the individual event size is too large (hundreds of megabytes), then you can modify the logstash pipeline to filter these events and re-start logstash.  The new pipeline will be used to process the events stuck in the queue.

**Comment by ebuildy** [comment]
As @lpkirby said, I managed to fix by reducing the ``pipeline.batch.size `` to 50. (we are running on Docker swarm).

BTW, this error is not explicit at all! Hard to figure out the root cause.

**Comment by lpkirby** [comment]
As a small update, the pipeline.batch.size helped, but what really finally did the trick was increasing the timeout in the Elasticsearch output.

I agree, this error is super generic and very hard to diagnose.

**Comment by ebuildy** [comment]
What timeout did you talk about? (I know only this one https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-timeout , and default value is 60s, quite big)

**Comment by lpkirby** [comment]
@ebuildy yeah, that's the one.  It's insane, but I had to change mine to 600.  I haven't had the chance to try and dig into why such a high timeout is required.  Ever since I did that, everything has been flowing smoothly even if a bit slow.

**Comment by lcshiung** [comment]
Encountered the "connection reset" issue. What worked for me was reducing pipeline.batch.size to a small number.

**Comment by raja-vunet** [comment]
We had this issue and after a long debugging, we found that this was caused by large volume of upserts.  We changed all of them to action => index and these errors went away.  In general from our experience we noticed that upserts are slowing down ES especially with large volume of data and we now prefer to just re-index the updated document with the same document_id.  Often we see version conflict errors with such volume of upserts which gets retried eventually.
