### ISSUE TITLE
Better exception handling in ILM check

### ISSUE THREAD

**Issue by andsel** [logstash-plugins/logstash-output-elasticsearch#907]
- Version: 10.2.1

Happened during ILM initialization because the logstash_writer did not had the correct privileges. The problem is that the client received a 403 error, but the logs doesn't cited it. The stack tarce a log is:
```
logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:80:in `perform_request'
logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:332:in `perform_request_to_url'
logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:319:in `block in perform_request'
logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:414:in `with_connection'
logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:318:in `perform_request'
logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:326:in `block in head'
logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:341:in `exists?'
logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:359:in `rollover_alias_exists?'
logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/ilm.rb:91:in `maybe_create_rollover_alias'
logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/ilm.rb:10:in `setup_ilm'
logstash-output-elasticsearch-10.2.1-java/lib/logstash/outputs/elasticsearch/common.rb:52:in `block in setup_after_successful_connection
```
The problem if that the execption is logged as:
```
[2019-12-17T12:43:12,913][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<LogStash::Outputs::elasticsearch::HttpClient::Pool::BadResponseCodeError: LogStash::Outputs::elasticsearch::HttpClient::Pool::BadResponseCodeError>, :backtrace=>[......
```
without any information from the exception, probably because the exception is bubled up from https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/v10.2.1/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb#L80 to https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/v10.2.1/lib/logstash/outputs/elasticsearch/common.rb#L49-L53
 that's run inside a new Thread without any exception handling.

**Comment by lachlann562** [comment]
if an alias is missing this really shouldn't cause a fatal error. Extremely frustrating that if someone adds a new configuration and forgets to setup the alias first that it completely prevents logstash from starting.
