### ISSUE TITLE
Add more detailed logging for ILM setup

### ISSUE THREAD

**Issue by n0othing** [logstash-plugins/logstash-output-elasticsearch#946]
(Tested on Logstash `7.7.1`)

The current "Configuring Security in Logstash" [1] docs has users configuring permissions for a `logstash-*` index pattern, which is inadequate for Logstash's default Index Lifecycle Management settings. There's an issue to address this [2] but it'd also be helpful to to add more logging to debug problems with the ILM setup process. Here's a snippet of logs which captures Logstash failing due to a lack of Security permissions:

```
[2020-06-15T09:58:03,892][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>12, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1500, "pipeline.sources"=>["/Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/logstash.conf"], :thread=>"#<Thread:0x22a6637 run>"}
[2020-06-15T09:58:03,917][INFO ][logstash.outputs.elasticsearch][main] Attempting to install template {:manage_template=>{"index_patterns"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s", "number_of_shards"=>1, "index.lifecycle.name"=>"logstash-policy", "index.lifecycle.rollover_alias"=>"logstash"}, "mappings"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}
[2020-06-15T09:58:03,940][INFO ][logstash.outputs.elasticsearch][main] Installing elasticsearch template to _template/logstash
warning: thread "Ruby-0-Thread-6: :1" terminated with exception (report_on_exception is true):
LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError: Got response code '403' contacting Elasticsearch at URL 'http://localhost:9200/logstash'
                    perform_request at /Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:80
             perform_request_to_url at /Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:332
                    perform_request at /Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:319
                    with_connection at /Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:414
                    perform_request at /Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:318
                               Pool at /Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:326
                            exists? at /Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:341
             rollover_alias_exists? at /Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:359
        maybe_create_rollover_alias at /Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/ilm.rb:91
                          setup_ilm at /Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/ilm.rb:10
  setup_after_successful_connection at /Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/common.rb:51
[2020-06-15T09:58:04,113][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError: LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError>, :backtrace=>["/Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:80:in `perform_request'", "/Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:332:in `perform_request_to_url'", "/Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:319:in `block in perform_request'", "/Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:414:in `with_connection'", "/Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:318:in `perform_request'", "/Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:326:in `block in Pool'", "/Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:341:in `exists?'", "/Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:359:in `rollover_alias_exists?'", "/Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/ilm.rb:91:in `maybe_create_rollover_alias'", "/Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/ilm.rb:10:in `setup_ilm'", "/Users/robbie/elastic/7.7_heartbeat_tls/logstash-7.7.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.4.2-java/lib/logstash/outputs/elasticsearch/common.rb:51:in `block in setup_after_successful_connection'"]}
[2020-06-15T09:58:04,126][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
```

The line capturing the `403` response is sort of helpful:

```
Got response code '403' contacting Elasticsearch at URL 'http://localhost:9200/logstash'
```

But there aren't any logs leading up to this point to know why Logstash was trying to reach out to `/logstash` in the first place (the previous log line is related to installing an index template, which actually succeeded).

[1] https://www.elastic.co/guide/en/logstash/current/ls-security.html
[2] https://github.com/elastic/logstash/issues/10722

**Comment by kaisecheng** [comment]
Thanks for reporting this issue. `v11.18.0` has enhanced the log message to provide the response body from Elasticsearch in case of error, which list the missing privileges.  

Please upgrade to the latest version of es-output and check out the latest [doc](https://www.elastic.co/guide/en/logstash/current/ls-security.html#ls-http-auth-basic). I believe it is enough information now.
