### ISSUE TITLE
add an assert to check returned item count from _bulk

### ISSUE THREAD

**Issue by kares** [logstash-plugins/logstash-output-elasticsearch#989]
we've seen some weird behavior on ES 7.10.2 where a **_bulk** request to index **69** documents returned **135** entries

this than leads to an ugly `NoMethodError: undefined method ``[]' for nil:NilClass`:
```
[ERROR][logstash.outputs.elasticsearch] Encountered an unexpected error submitting a bulk request! Will retry. {:error_message=>"undefined method `[]' for nil:NilClass", :class=>"NoMethodError", :backtrace=>["/u01/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.7.3-java/lib/logstash/outputs/elasticsearch/common.rb:311:in `block in submit'", "org/jruby/RubyArray.java:1809:in `each'", "org/jruby/RubyEnumerable.java:1258:in `each_with_index'", "/u01/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.7.3-java/lib/logstash/outputs/elasticsearch/common.rb:305:in `submit'", "/u01/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.7.3-java/lib/logstash/outputs/elasticsearch/common.rb:257:in `retrying_submit'", "/u01/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.7.3-java/lib/logstash/outputs/elasticsearch/common.rb:36:in `multi_receive'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:143:in `multi_receive'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:121:in `multi_receive'", "/u01/logstash/logstash-core/lib/logstash/java_pipeline.rb:295:in `block in start_workers'"]}
```

asserting the returned (`{"took":0,"ingest_took":9,"errors":true,"items":[{"index":{"_index": ...`) `json['items']` might be an easy hint to quickly identify the issue.

**Comment by kares** [comment]
the likely cause from ES: https://github.com/elastic/elasticsearch/pull/60818
